name: cnctorch-tpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - numpy
  - scipy
  - h5py
  - tqdm
  - pip
  - pip:
      - torch>=2.1
      - torch_xla>=2.1
      - open3d
      - pysdf
      - trimesh
      - PyMCubes
      - pymesh2
      - plyfile
