name: cnctorch-tpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - h5py
  - tqdm
  - pip
  - pip:
      - --find-links https://storage.googleapis.com/libtpu-releases/index.html
      - torch==2.8.0
      - torch_xla[tpu]==2.8.0
      - open3d
      - pysdf
      - trimesh
      - PyMCubes
      - ./required/pymesh2-0.3.1-cp310-cp310-linux_x86_64.whl
      - plyfile
